mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from .views import HomePageView, SignUpView, JugarTemplateView, add
from trivias.views import ranking

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup', SignUpView.as_view(), name='signup'),
    path('', HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('sumando', add, name='add-name'),
    path('pregunta/', include('preguntas.urls')),
    path('jugar/', JugarTemplateView.as_view(), name='jugar'),
    path('ranking/', ranking, name='ranking')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

preguntas/urls.py
from django.urls import path
from .views import (
    PreguntaListView, PreguntaDetailView, preguntadetailrandom,
    getpreguntasfacil, getreguntasnormal, getpreguntasdificil,
    resultadopregunta
)


urlpatterns = [
    path('', PreguntaListView.as_view(), name='pregunta-list'),
    path('<int:pk>/', PreguntaDetailView.as_view(), name='pregunta-detail'),
    # path('random/', preguntadetailrandom, name='pregunta-detail-random'),
    path('facil/', getpreguntasfacil, name='preguntas-facil'),
    path('normal/', getreguntasnormal, name='preguntas-normal'),
    path('dificil/', getpreguntasdificil, name='preguntas-dificil'),
    path('resultado/', resultadopregunta, name='resultado')
]

preguntas/models.py
from django.db import models
import random

class Pregunta(models.Model):
    CATEGORIA_CHOICES = [
        (1, 'Ciencia y Educación'),
        (2, 'Cultura y arte'),
        (3, 'Deporte'),
        (4, 'Economía'),
        (5, 'Entretenimiento'),
        (6, 'Historia'),
        (7, 'Geografía'),
    ]

    NIVEL_CHOICES = [
        (1, "Facil"),
        (2, "Normal"),
        (3, "Dificil"),
    ]

    texto = models.CharField(max_length=200)
    categoria = models.PositiveSmallIntegerField(
        'categoria',
        choices=CATEGORIA_CHOICES,
        default=6
    )
    nivel = models.PositiveSmallIntegerField(
        'dificultad',
        choices=NIVEL_CHOICES,
        default=2
    )

    def __str__(self):
        return f"{self.texto} ({self.get_nivel_display()})"

    def get_rtas_correctas(self):
        rtas = Respuesta.objects.filter(pregunta=self.id, correcta=True)
        return rtas

    def respuesta_es_correcta(self, rta):
        rtas = self.get_rtas_correctas()
        col_id = []
        for r in rtas:
            col_id.append(r.id)
        if rta in col_id:
            return True
        else:
            return False

    def get_respuestas(self):
        rtas = list(Respuesta.objects.filter(pregunta=self.id))
        random.shuffle(rtas)
        return rtas

    def get_respuestas_ok(self):
        rtas = list(Respuesta.objects.filter(pregunta=self.id, correcta=True))
        # salida = f'{len(rtas)} \n'
        salida = ''
         # en el admin si queda lindo
        # for idx, r in enumerate(rtas, start=1):
        #     salida += f"{idx}){r.texto}.\n"
        # return salida
        for r in rtas:
            salida += f"{r.texto}"
            # salida += f"id: {r.id} - {r.texto}"
        return salida
    get_respuestas_ok.short_description = "Rtas Correctas"

    def get_respuestas_random(self):
        respuestas = list(Respuesta.objects.filter(pregunta=self.id))
        random.shuffle(respuestas)
        return respuestas

    def cant_rtas(self):
        return Respuesta.objects.filter(pregunta=self.id).count()
    cant_rtas.short_description = "Respuestas"

    def cant_rtas_ok(self):
        return Respuesta.objects.filter(pregunta=self.id, correcta=True).count()
    cant_rtas_ok.short_description = "Rtas Correctas"


class Respuesta(models.Model):
    texto = models.CharField(max_length=200)
    pregunta = models.ForeignKey(
        Pregunta,
        on_delete=models.CASCADE,
        related_name='respuesta'
    )
    correcta = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.texto} (V)" if self.correcta else f"{self.texto} (F)"

    def short(self):
        return f"{self.pregunta.texto[:60]} ..."
    short.short_description = "Pregunta"

preguntas/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Pregunta, Respuesta
from trivias.models import Juego
from django.contrib.auth.decorators import login_required


class PreguntaListView(ListView):
    model = Pregunta


class PreguntaDetailView(DetailView):
    model = Pregunta


def preguntadetailrandom(request):
    # pregunta = Pregunta.objects.order_by("?").first()
    pregunta = Pregunta.objects.order_by("?")[:10]
    template = "preguntas/pregunta_detail.html"
    return render(request, template, {"object": pregunta})


@login_required
def getpreguntasfacil(request):
    context = {}
    preguntas = Pregunta.objects.filter(nivel=1).order_by("?")[:10]
    # template = "preguntas/pregunta_list.html"
    template = "preguntas/pregunta_listado.html"
    context["object_list"] = preguntas
    context["nivel"] = "(Facil)"
    return render(request, template, context)


@login_required
def getreguntasnormal(request):
    context = {}
    preguntas = Pregunta.objects.filter(nivel=2).order_by("?")[:10]
    # preguntas = Pregunta.objects.order_by("?")[:10]
    # preguntas = Pregunta.objects.filter(nivel=2)[:5]
    template = "preguntas/pregunta_listado.html"
    context["object_list"] = preguntas
    context["nivel"] = "(Normal)"
    return render(request, template_name=template, context=context)


@login_required
def getpreguntasdificil(request):
    context = {}
    preguntas = Pregunta.objects.filter(nivel=3).order_by("?")[:10]
    # template = "preguntas/pregunta_list.html"
    template = "preguntas/pregunta_listado.html"
    context["object_list"] = preguntas
    context["nivel"] = "(Dificil)"
    return render(request, template, context)


@login_required
def resultadopregunta(request):
    context = {}
    template = "resultado.html"
    preg_id = []
    dic_p_r = {}
    cont_correcta = 0
    for key, value in request.POST.items():
        # key es la pregunta_id
        # value es la respuesta que se eligio
        if key != 'csrfmiddlewaretoken':
            # print(f'Pregunta_id: {key}')
            # print(f'Rta: {value}')
            rta_selec = Respuesta.objects.get(pk=value)
            llave = int(key)
            dic_p_r[llave] = rta_selec
            preg_id.append(key)
            pregunta = Pregunta.objects.get(pk=key)
            if pregunta.respuesta_es_correcta(int(value)):
                cont_correcta += 1

    # preg_id, es una coleccion de las preguntas_id
    preguntas_originales = Pregunta.objects.filter(pk__in=preg_id)
    dificultad = preguntas_originales[0].nivel
    context['preguntas_originales'] = preguntas_originales
    context['respuestas_sel'] = dic_p_r
    context['correctas'] = cont_correcta

    # creo el nuevo juego
    juego = Juego(
        user=request.user,
        nivel=dificultad,
        puntaje=cont_correcta
    )
    juego.save()
    return render(request, template, context)

preguntas/templates/preguntas/pregunta_detail.html
{% extends "base.html" %}

{% block title %}Pregunta{% endblock title %}

{% block content %}
<br>
<br>
<div class="container">

    <div class="card border-primary mb-3" style="max-width: 75%;">
        <div class="card-header">
            <i>{{object.get_categoria_display}}</i>
        </div>
        <div class="card-body text-dark">
            <h4 class="card-title"><strong>{{object.texto}}</strong></h4>
            <h3>{{usuario.usuario}} puntaje {{usuario.puntaje}}</h3>
            <p class="card-text">
                <ul class="list-group">
                    {% for rta in object.get_respuestas_random %}
                        {% if rta.correcta %}
                            <li id="{{ forloop.counter }}" onclick="correcto(id)" class="list-group-item list-group-item-light correcta">
                                <strong>{{ forloop.counter }}.</strong> {{rta.texto}}
                            </li>
                        {% else %}
                            <li id="{{ forloop.counter }}" onclick="incorrecto(id)" class="list-group-item list-group-item-light incorrecta">
                                <strong>{{ forloop.counter }}.</strong> {{rta.texto}}
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </p>
        </div>
    </div>


</div>
<script>
    function correcto(a) {
        document.getElementById(a).style.backgroundColor = "#d1e7dd";
    }
    function incorrecto(b) {
        document.getElementById(b).style.backgroundColor = "#f8d7da";
    }
</script>

{% endblock content %}

preguntas/templates/preguntas/pregunta_list.html
{% extends "base.html" %}
{% block title %}Listado Preguntas{% endblock title %}
{% block content %}

<h1>Listado de Preguntas</h1>
<hr>
<div class="row">
{% for pregunta in object_list %}


    <div class="col">
        <div class="card" style="width: 20rem;">
        <div class="card-header">{{pregunta.texto}}</div>
        {% if pregunta.respuesta.all %}
            <ul class="list-group list-group-flush">
                {% for respuesta in pregunta.respuestas.all %}
                    <li class="list-group-item">{{respuesta.texto}}</li>
                {% endfor %}
            </ul>
        {% else %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">NADA</li>
            </ul>
        {% endif %}
    </div>
    </div>
{% endfor %}
</div>


{% endblock content %}

preguntas/templates/preguntas/pregunta_listado.html
{% extends "base.html" %}
{% block title %}Listado Preguntas{% endblock title %}
{% block content %}
<h1 class="h55">Listado de Preguntas <i>{{nivel}}</i></h1>
<div class="row">
    <form action="{% url 'resultado' %}" method="POST">{% csrf_token %}
        <div class="form-container">
    {% for pregunta in object_list %}
        
        <div class="card border-primary mb-3 container_form" style="max-width: 75%;">
            <div class="card-header">
                <i>{{pregunta.get_categoria_display}}</i>
            </div>
            <div class="card-body text-dark">
                <h4 class="card-title"><strong>{{ forloop.counter }}) {{pregunta.texto}}</strong></h4>

                <p class="card-text">
                    <ul class="list-group">
                        {% for rta in pregunta.get_respuestas_random %}
                            <li class="list-group-item list-group-item-light">
                                <input type="radio" id="{{pregunta.id}}" name="{{pregunta.id}}" value={{rta.id}}>
                                <label for="{{pregunta.id}}">{{rta.texto}}</label><br>
                                {% comment %}
                                <label for="{{pregunta.id}}">{{rta.texto}} {{rta.correcta |yesno:"(V),(F),que paso aqui?" }} </label><br>
                                {% endcomment %}
                            </li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
        </div>

    {% endfor %}
        <input type="submit" value="Enviar">
        </div>
    </form>
</div>

{% endblock content %}